batch_size: 4
device: cuda:0
file_rename: false
input_file: data/instructions/test/llama3.1/autodan_llama3.1.json
max_new_tokens: 128
model_name: llama3.1
output_file: data/responses/llama3.1/rv/autodan_llama3.1_rv_results.json
prompt_column: query
steering_vector_path: data/refusal_vectors/RV/llama3.1_RV_refusal.pkl
strength: 0.0,0.1,0.2,0.3,0.4,0.5
