device: cuda:3
model_name: gemma2
input_file: data/instructions/test/xstest_safe.json
output_file: data/responses/gemma2/xstest_gemma2_rfm_results_gemma2_agopn_gemma2_rc_nons_full.json
batch_size: 1
max_new_tokens: 128
file_rename: False
prompt_column: prompt
strength: "0.0,0.3,0.5,0.7,0.9,1.0,1.3,1.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0"
steering_matrix_path: data/steering_matrix/steering_matrix_gemma2_rfm_rc_full_no_nullspace.pt
