device: cuda:0
model_name: gemma2
steering_matrix_path: data/steering_matrix/steering_matrix_gemma2_rfm.pt
input_file: data/instructions/test/gemma2/pair_gemma2.json
output_file: data/responses/gemma2/pair_gemma2_rfm_results.json
batch_size: 1
max_new_tokens: 128
file_rename: False
prompt_column: query
strength: -3,-2.5,-2,-1.5,-1,-0.8,-0.5,0,0.5,0.8,1,1.5,2,2.5,3