batch_size: 2
device: cuda:0
file_rename: false
input_file: experimental/smoke_test_topk10/inputs/qwen2.5/math_2sample.json
max_new_tokens: 4096
model_name: qwen2.5
output_file: experimental/smoke_test_topk10/outputs/qwen2.5/math_qwen2.5_smoketest.json
prompt_column: problem
steering_matrix_path: data/steering_matrix/steering_matrix_qwen2.5_rfm_rc_full_hard_refusal_topk10.pt
strength: 0.0,4.0,5.0,6.0,7.0
