device: auto
model_name: llama3.3-70b
steering_matrix_path: data/steering_matrix/steering_matrix_llama3.3-70b_rfm_no_nullspace.pt
input_file: data/instructions/test/math_500_sampled.json
output_file: data/responses/llama3.3-70b/math_llama3.3-70b_rfm_results.json
batch_size: 4
max_new_tokens: 4096
file_rename: False
prompt_column: problem
strength: 0.0,0.5