device: auto
model_name: llama3.1
steering_matrix_path: data/steering_matrix/steering_matrix_llama3.1_rfm_no_nullspace.pt
input_file: data/instructions/test/math_500_sampled.json
output_file: data/responses/llama3.1/math_llama3.1_rfm_no_nullspace_results.json
batch_size: 64
max_new_tokens: 4096
file_rename: False
prompt_column: problem
strength: 0.75,0.11